# fly.toml app configuration file generated for test-auth on 2024-09-03T17:43:42+01:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

# WARNING
# If this file is committed to a public repo, don't use it for secrets.

app = 'test-auth'
primary_region = 'ams'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = false
auto_stop_machines = 'off'
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
memory = 256

[env]
APP = 'https://test-auth.jldec.me'
PORT = '3000'
AUTH = 'pub-pkg-google-oauth'
REDIS = '1'

